baseUrl:        https://corcel.io
languageCode:   en-gb
title:          Corcel
theme:          theme.corcel.io
canonifyUrls:   true
params:
  # General information
  author:      Guzzler.io
  description: Documentation for Corcel
  copyright:   Released under my prefered license

  # Repository
  provider:   GitHub
  repoUrl:    https://github.com/guzzlerio/corcel.io
  repoId:     corcel.io

  version:     1.0.0
  # favicon:     favicon.ico

  permalink:   "#"
  siteLinks:
      - Label:   Downloads
        URL:     https://corcel.io/downloads
      - Label:   Documentation
        URL:     http://docs.corcel.io
      - Label:   Blog
        URL:     https://blog.corcel.io
      - Label:   Feedback
        URL:     https://corcel.io/feedback

  social:
    github:    guzzlerio
...
